// Renders a CertificateData object (see lib/certificate.js) into a downloadable
// PDF using jsPDF's vector text/shape primitives — never a screenshot of the
// on-screen preview, so the exported document stays crisp and the text stays
// selectable. Mirrors the same 8 sections shown in
// components/certificate/PropertyCertificateModal.jsx and uses no data beyond
// what that modal was already given.

import { jsPDF } from 'jspdf'
import { NA } from './certificate.js'
import { boundaryToDataUrl } from './boundaryMap.js'

const PAGE_W = 210 // A4 mm
const PAGE_H = 297
const MARGIN = 16
const CONTENT_W = PAGE_W - MARGIN * 2
const FOOTER_TEXT =
  'This certificate is generated by the 3D ULPIN prototype and does not constitute an official government land ' +
  'title/certificate unless explicitly issued by the competent authority.'

const INK = [30, 41, 59] // slate-800
const MUTED = [100, 116, 139] // slate-500
const RULE = [226, 232, 240] // slate-200
const AMBER = [180, 83, 9] // amber-700 / warn
const EMERALD = [150, 106, 27] // brass — matches the app's "official source" accent
const TEAL = [15, 118, 110] // matches the app's "verified" accent (used for the 3D ULPIN)

function fmtDate(iso) {
  if (!iso) return NA
  const d = new Date(iso)
  return Number.isNaN(d.getTime()) ? String(iso) : d.toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' })
}

class Cursor {
  constructor(doc) {
    this.doc = doc
    this.y = 0
  }

  ensureSpace(h) {
    if (this.y + h > PAGE_H - MARGIN - 12) {
      this.doc.addPage()
      this.y = MARGIN
    }
  }

  gap(h) {
    this.y += h
  }
}

function drawRow(doc, cursor, label, value) {
  const text = value === null || value === undefined || value === '' ? NA : String(value)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9)
  doc.setTextColor(...MUTED)
  const labelW = 55
  const valueW = CONTENT_W - labelW - 2
  const lines = doc.splitTextToSize(text, valueW)
  const lineH = 4.2
  const h = Math.max(lineH, lines.length * lineH) + 1.5
  cursor.ensureSpace(h)
  doc.text(label, MARGIN + 2, cursor.y + 3.4)
  doc.setTextColor(...INK)
  doc.setFont('helvetica', 'bold')
  doc.text(lines, MARGIN + labelW, cursor.y + 3.4)
  doc.setDrawColor(...RULE)
  doc.setLineWidth(0.15)
  doc.line(MARGIN, cursor.y + h - 0.5, MARGIN + CONTENT_W, cursor.y + h - 0.5)
  cursor.gap(h)
}

function sectionHeader(doc, cursor, n, title) {
  cursor.ensureSpace(9)
  doc.setFillColor(51, 65, 85) // slate-700
  doc.circle(MARGIN + 2, cursor.y + 2.6, 2.2, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(7)
  doc.text(String(n), MARGIN + 2, cursor.y + 3.3, { align: 'center' })
  doc.setTextColor(...MUTED)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(9)
  doc.text(title.toUpperCase(), MARGIN + 6, cursor.y + 3.4)
  cursor.gap(7)
}

function note(doc, cursor, text, color = MUTED) {
  doc.setFont('helvetica', 'italic')
  doc.setFontSize(7.5)
  doc.setTextColor(...color)
  const lines = doc.splitTextToSize(text, CONTENT_W - 2)
  const h = lines.length * 3.6 + 2
  cursor.ensureSpace(h)
  doc.text(lines, MARGIN + 2, cursor.y + 3)
  cursor.gap(h)
}

function sectionGap(cursor) {
  cursor.gap(4)
}

function threeDUlpinBox(doc, cursor, ulpin) {
  const h = 8
  cursor.ensureSpace(h + 1.5)
  doc.setFillColor(240, 253, 250) // teal-50
  doc.setDrawColor(153, 246, 228) // teal-200
  doc.roundedRect(MARGIN, cursor.y, CONTENT_W, h, 1, 1, 'FD')
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(8)
  doc.setTextColor(...TEAL)
  doc.text('3D ULPIN', MARGIN + 3, cursor.y + h / 2 + 1.2)
  doc.setFontSize(10)
  doc.text(String(ulpin), MARGIN + CONTENT_W - 3, cursor.y + h / 2 + 1.4, { align: 'right' })
  cursor.gap(h + 1.5)
}

function drawHeader(doc, data) {
  doc.setFillColor(30, 41, 59) // slate-800
  doc.rect(0, 0, PAGE_W, 1.4, 'F')

  doc.setTextColor(...MUTED)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(7.5)
  doc.text('CHENNAI 3D CADASTRE · PROTOTYPE', MARGIN, 12)

  doc.setTextColor(...INK)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(17)
  doc.text('3D PROPERTY CERTIFICATE', MARGIN, 20)

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9)
  doc.setTextColor(...MUTED)
  doc.text('Land & Property Information | 3D Cadastre Prototype', MARGIN, 25.5)

  const badgeText = data.identity.verificationLabel
  const isOfficial = data.identity.verificationStatus === 'OFFICIAL'
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(8)
  const badgeColor = isOfficial ? EMERALD : AMBER
  doc.setTextColor(...badgeColor)
  doc.text(badgeText, PAGE_W - MARGIN, 12, { align: 'right' })
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(7.5)
  doc.setTextColor(...MUTED)
  doc.text(`Generated ${fmtDate(data.generatedAtISO)}`, PAGE_W - MARGIN, 16.5, { align: 'right' })

  doc.setDrawColor(...INK)
  doc.setLineWidth(0.5)
  doc.line(MARGIN, 28.5, PAGE_W - MARGIN, 28.5)

  // Prototype disclaimer strip
  doc.setFillColor(255, 251, 235) // amber-50
  doc.setDrawColor(252, 211, 77) // amber-300
  doc.roundedRect(MARGIN, 31, CONTENT_W, 9, 1.2, 1.2, 'FD')
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(7.5)
  doc.setTextColor(...AMBER)
  doc.text('Prototype.', MARGIN + 2.5, 35.3)
  doc.setFont('helvetica', 'normal')
  const disc = doc.splitTextToSize(
    'This certificate is generated by the 3D ULPIN prototype and does not constitute an official government land title or certificate.',
    CONTENT_W - 32,
  )
  doc.text(disc, MARGIN + 32, 35.3)

  return 44 // starting Y for section content
}

function stampFootersAndPageNumbers(doc) {
  const total = doc.internal.getNumberOfPages()
  for (let i = 1; i <= total; i += 1) {
    doc.setPage(i)
    doc.setDrawColor(...RULE)
    doc.setLineWidth(0.2)
    doc.line(MARGIN, PAGE_H - 16, PAGE_W - MARGIN, PAGE_H - 16)
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(6.5)
    doc.setTextColor(...MUTED)
    const lines = doc.splitTextToSize(FOOTER_TEXT, CONTENT_W)
    doc.text(lines, PAGE_W / 2, PAGE_H - 12, { align: 'center' })
    doc.text(`Page ${i} of ${total}`, PAGE_W - MARGIN, PAGE_H - 5, { align: 'right' })
  }
}

export async function generateCertificatePdf(data, qrDataUrl) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' })
  const cursor = new Cursor(doc)
  cursor.y = drawHeader(doc, data)

  // 1. Property Identity
  sectionHeader(doc, cursor, 1, 'Property Identity')
  drawRow(doc, cursor, 'ULPIN', data.identity.ulpin)
  drawRow(doc, cursor, 'ULPIN Kind', data.identity.ulpinKind)
  drawRow(doc, cursor, 'Verification Status', data.identity.verificationLabel)
  drawRow(doc, cursor, 'Data Source', data.identity.dataSource)
  drawRow(doc, cursor, 'Record / Reference ID', data.identity.recordId)
  if (data.identity.note) note(doc, cursor, data.identity.note)
  sectionGap(cursor)

  // 2. Owner Information
  sectionHeader(doc, cursor, 2, 'Owner Information')
  if (data.owner.current.length > 0) {
    data.owner.current.forEach((o, i) => {
      drawRow(doc, cursor, i === 0 ? 'Current Owner(s)' : '', [o.name, o.sharePct != null ? `${o.sharePct}%` : null].filter(Boolean).join(' — '))
    })
  } else {
    drawRow(doc, cursor, 'Current Owner(s)', NA)
  }
  drawRow(doc, cursor, 'Ownership Status', data.owner.ownershipStatus)
  drawRow(doc, cursor, 'Previous Holder(s)', data.owner.previousHolders?.length ? data.owner.previousHolders.join(', ') : NA)
  drawRow(doc, cursor, 'Mutation / Transfer Date', data.owner.mutationDate ? fmtDate(data.owner.mutationDate) : NA)
  note(doc, cursor, 'Owner contact information is not exposed on this certificate. PROTOTYPE — synthetic names only, no real personal information.')
  sectionGap(cursor)

  // 3. Parcel Information
  sectionHeader(doc, cursor, 3, 'Parcel Information')
  drawRow(doc, cursor, 'Survey Number', data.parcel.surveyNumber)
  drawRow(doc, cursor, 'Subdivision Number', data.parcel.subdivisionNumber)
  drawRow(
    doc, cursor, 'Area',
    data.parcel.areaSqft != null
      ? `${data.parcel.areaSqft.toLocaleString('en-IN')} sq.ft${data.parcel.areaSqm != null ? ` (${data.parcel.areaSqm.toLocaleString('en-IN')} m²)` : ''}`
      : NA,
  )
  drawRow(doc, cursor, 'Land Use', data.parcel.landUse)
  drawRow(doc, cursor, 'Property Type', data.parcel.propertyType)
  drawRow(doc, cursor, 'District', data.parcel.district)
  drawRow(doc, cursor, 'Taluk', data.parcel.taluk)
  drawRow(doc, cursor, 'Village / Locality', data.parcel.village)
  sectionGap(cursor)

  // 4. Spatial Information
  sectionHeader(doc, cursor, 4, 'Spatial Information')
  drawRow(doc, cursor, 'Centroid Latitude', data.spatial.centroid ? data.spatial.centroid.lat.toFixed(6) : NA)
  drawRow(doc, cursor, 'Centroid Longitude', data.spatial.centroid ? data.spatial.centroid.lon.toFixed(6) : NA)
  drawRow(doc, cursor, 'CRS', data.spatial.crs || NA)
  note(doc, cursor, 'ULPIN is the parcel identifier — its characters are not latitude/longitude. Coordinates above are separate, supporting spatial information.')
  cursor.gap(1)

  const mapW = 80
  const mapH = 50
  cursor.ensureSpace(mapH + 8)
  const mapDataUrl = boundaryToDataUrl(data.spatial.boundary?.ring || null, { width: mapW * 6, height: mapH * 6 })
  doc.addImage(mapDataUrl, 'PNG', MARGIN + 2, cursor.y, mapW, mapH)
  doc.setDrawColor(...RULE)
  doc.rect(MARGIN + 2, cursor.y, mapW, mapH)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(7)
  doc.setTextColor(...MUTED)
  const capLines = doc.splitTextToSize(data.spatial.boundary?.label || 'Boundary — Not Available', CONTENT_W - mapW - 8)
  doc.text(capLines, MARGIN + mapW + 8, cursor.y + 4)
  if (data.spatial.isDemoCoordinates) {
    doc.setTextColor(...AMBER)
    doc.text('Prototype coordinates — not a surveyed position.', MARGIN + mapW + 8, cursor.y + 4 + capLines.length * 3.6 + 3)
  }
  cursor.gap(mapH + 6)
  sectionGap(cursor)

  // 5. Registration / Legal-Status Information
  sectionHeader(doc, cursor, 5, 'Registration / Legal-Status Information')
  drawRow(doc, cursor, 'Registration Reference', data.legal.registrationRef)
  drawRow(doc, cursor, 'Encumbrance Status', data.legal.encumbranceStatus)
  drawRow(doc, cursor, 'Land Restriction / Remarks', data.legal.remarks)
  drawRow(doc, cursor, 'Court / Litigation Status', data.legal.litigationStatus)
  sectionGap(cursor)

  // 6. 3D Property Information
  sectionHeader(doc, cursor, 6, '3D Property Information')
  const t = data.threeD || {}
  if (data.kind === 'parcel') {
    drawRow(doc, cursor, 'Buildings on Parcel', t.buildingCount)
    drawRow(doc, cursor, 'Floors (rollup)', t.floorCount)
    drawRow(doc, cursor, 'Units (rollup)', t.unitCount)
  } else {
    if (t.threeDUlpin) threeDUlpinBox(doc, cursor, t.threeDUlpin)
    drawRow(doc, cursor, 'Building ID', t.buildingId)
    if (data.kind === 'unit') {
      drawRow(doc, cursor, 'Floor ID', t.floorId)
      drawRow(doc, cursor, 'Unit ID', t.unitId)
    }
    if (data.kind === 'building') {
      drawRow(doc, cursor, 'Number of Floors', t.totalFloors)
      drawRow(doc, cursor, 'Number of Units', t.totalUnits)
    }
    drawRow(doc, cursor, 'Building Height', t.buildingHeightM != null ? `${t.buildingHeightM} m` : NA)
    drawRow(doc, cursor, '3D Volume ID', t.volumeId)
    drawRow(
      doc, cursor, 'X/Y/Z Bounds',
      t.bounds
        ? `X ${t.bounds.xmin?.toFixed?.(6)}…${t.bounds.xmax?.toFixed?.(6)}, Y ${t.bounds.ymin?.toFixed?.(6)}…${t.bounds.ymax?.toFixed?.(6)}, Z ${t.bounds.zmin ?? '—'}…${t.bounds.zmax ?? '—'}`
        : NA,
    )
    drawRow(doc, cursor, 'Estimated Volume', t.estVolumeM3 != null ? `${t.estVolumeM3} m³` : NA)
    drawRow(doc, cursor, 'Geometry Status', t.geometryStatus)
  }
  note(doc, cursor, '3D ULPIN, Building ID, Floor ID, Unit ID and Volume ID are system-generated / prototype identifiers — never an official government ULPIN.')
  sectionGap(cursor)

  // 7. Data Provenance
  sectionHeader(doc, cursor, 7, 'Data Provenance')
  drawRow(doc, cursor, 'Source', data.provenance.source)
  drawRow(doc, cursor, 'Verification Status', data.provenance.verificationStatus)
  drawRow(doc, cursor, 'Generated Date', fmtDate(data.generatedAtISO))
  drawRow(doc, cursor, 'Record Version / Timestamp', data.provenance.recordVersion ?? data.generatedAtISO)
  if (data.generatedByLine) drawRow(doc, cursor, 'Generated By', data.generatedByLine)
  if (data.provenance.disclaimer) note(doc, cursor, data.provenance.disclaimer, AMBER)
  sectionGap(cursor)

  // 8. QR Code
  sectionHeader(doc, cursor, 8, 'QR Code')
  const qrSize = 26
  cursor.ensureSpace(qrSize + 4)
  if (qrDataUrl) {
    doc.addImage(qrDataUrl, 'PNG', MARGIN + 2, cursor.y, qrSize, qrSize)
  } else {
    doc.setDrawColor(...RULE)
    doc.rect(MARGIN + 2, cursor.y, qrSize, qrSize)
  }
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(7.5)
  doc.setTextColor(...MUTED)
  doc.text('Scan to open this property in the application:', MARGIN + qrSize + 10, cursor.y + 5)
  doc.setFont('courier', 'normal')
  doc.setFontSize(6.5)
  const urlLines = doc.splitTextToSize(data.qrUrl, CONTENT_W - qrSize - 12)
  doc.text(urlLines, MARGIN + qrSize + 10, cursor.y + 10)
  cursor.gap(qrSize + 4)

  stampFootersAndPageNumbers(doc)

  const filenameSafe = (data.identity.recordId || data.title || 'certificate').replace(/[^A-Za-z0-9._-]+/g, '_')
  doc.save(`3D-Property-Certificate-${filenameSafe}.pdf`)
}
