// Client-side mirror of backend/src/config/rbac.js — used only for optimistic
// UI gating before GET /api/auth/me returns the authoritative list. The backend
// always re-checks on every request. Keep this in sync with rbac.js: the Phase
// 7/8/9 verbs below matter because a hard reload renders the app from the JWT
// (role only) before /auth/me resolves, and a missing verb briefly hides the
// Topology / Underground / 3D-Identifier nav and disables their actions.
export const PERMISSIONS = {
  Citizen: [
    'parcel:search',
    'parcel:view-public',
    'property:view-public',
    'service:create',
    'service:track',
    'gis:view',
    'report:view-own',
    'infrastructure:read',
    '3didentifier:read',
  ],
  'Land Officer': [
    'parcel:search',
    'parcel:view',
    'parcel:verify',
    'ror:view',
    'ror:update',
    'property:view',
    'property:verify',
    'encumbrance:view',
    'registration:view',
    'dispute:view',
    'service:process',
    'gis:view',
    'audit:view-own',
    'report:view',
    'topology:read',
    'infrastructure:read',
    '3didentifier:read',
    '3dulpin:create',
  ],
  'Survey Officer': [
    'parcel:search',
    'parcel:view',
    'parcel:boundary-review',
    'survey:update',
    'property:view',
    'gis:view',
    'ai:run',
    'change-detection:review',
    'report:view',
    'topology:read',
    'topology:validate',
    'topology:review',
    'infrastructure:read',
    'infrastructure:upload',
    'infrastructure:validate',
    'infrastructure:review',
    '3didentifier:read',
    '3didentifier:create',
    '3didentifier:validate',
    '3didentifier:review',
  ],
  'Planning Officer': [
    'parcel:search',
    'parcel:view',
    'building-approval:view',
    'building-approval:update',
    'landuse:view',
    'landuse:update',
    'masterplan:view',
    'property:view',
    'gis:view',
    'report:view',
    'topology:read',
    'infrastructure:read',
    '3didentifier:read',
  ],
  'Revenue Officer': [
    'parcel:search',
    'parcel:view',
    'tax:view',
    'tax:update',
    'property:view',
    'gis:view',
    'report:view',
    'infrastructure:read',
    '3didentifier:read',
  ],
  Administrator: ['*'],
}

export const permissionsFor = (role) => PERMISSIONS[role] || []
